image: docker:latest

services:
  - docker:dind

build:
  stage: build
  only:
    refs:
      - master
  script:
    - apk add bash git
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - bash scripts/ci-build.sh
