image: docker:alpine

services:
  - docker:dind

build:
  stage: build
  only:
    - tags
    - branches
  script:
    - apk --update add git bash
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - bash scripts/ci-build.sh
