version: '2'
services:
  adblock_dns:
    image: ragibkl/adblock_dns
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
    env_file:
      - .env

  adblock_http:
    image: ragibkl/adblock_http
    restart: always
    ports:
      - 80:80
      - 443:443
