version: '3'

services:
  adblock_dns:
    image: ragibkl/adblock_dns:default
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "20"
    volumes:
      - logs:/logs

  adblock_http:
    image: ragibkl/adblock_http
    restart: always
    ports:
      - 80:80
      - 443:443
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "20"

  logs_viewer:
    image: node
    user: node
    working_dir: /app
    volumes:
      - ./logs-viewer:/app
      - logs:/logs
    ports:
      - 8080:8080
    command: "yarn start"

volumes:
  logs:
