version: '3'

services:
  adblock_dns:
    image: ragibkl/adblock_dns
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      FQDN: dns.localhost.localdomain
      IPV4: 127.0.0.1
      IPv6: ::1

  adblock_http:
    image: ragibkl/adblock_http
    restart: always
    ports:
      - 80:80
      - 443:443
