version: '3'

services:
  adblock_dns:
    image: ragibkl/adblock_dns:base
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - ./data/output.d/blacklist.zone:/templates/blacklist.zone
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "20"

  adblock_http:
    image: ragibkl/adblock_http
    restart: always
    ports:
      - 80:80
      - 443:443
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "20"
